color_dict ={
    "Sokka" : "blue",
    "Katara" : "blue",
    "Aang" : "white",
	"Appa" : "other",
	"Kanna" : "blue",
    "Iroh" : "red",
    "Zuko" : "red",
    "Zhao" : "red",
    "Gyatso" : "white",
	"Momo" : "other",
	"Oyagi" : "green",
	"Suki" : "green",
	"Cabbage Merchant" : "green",
	"Bumi" : "green",
	"Flopsy" : "other",
	"Haru" : "green",
	"Ozai" : "red",
	"Tyro" : "green",
	"Hei-Bai" : "other",
	"Roku" : "red",
	"Kyoshi" : "green",
	"Koko" : "green",
	"Actor Bumi" : "red",
	"Actor Iroh" : "red",
	"Actor Jet" : "red",
	"Actor Sokka" : "red",
	"Actor Toph" : "red",
	"Actor Zuko" : "red",
	"Actress Azula" : "red",
	"Actress Katara" : "red",
	"Actress Yue" : "red",
	"Arnook" : "blue",
	"Azula" : "red",
	"Azulon" : "red",
	"Bato" : "blue",
	"Bosco" : "green",
	"The Boulder" : "green",
	"Canyon Guide" : "green",
	"Chan" : "red",
	"Chey" : "red",
	"Chin" : "green",
	"Chit Sang" : "red",
	"Chong" : "green",
	"Circus Master" : "red",
	"Combustion Man" : "red",
	"Ding" : "red",
	"Dock" : "red",
	"Due" : "blue",
	"Fang" : "other",
	"Fat" : "red",
	"Fong" : "green",
	"Gan Jin Leader" : "green",
	"Gan Jin Scout" : "green",
	"Gansu" : "green",
	"Ghashiun" : "green",
	"Governor" : "red",
	"Governor's Wife" : "red",
	"Gow" : "green",
	"Guru" : "other",
	"Hahn" : "blue",
	"Hakoda" : "blue",
	"Ham Ghao" : "red",
	"Hama" : "blue",
	"Hawky" : "other",
	"Herbalist" : "green",
	"Hide" : "red",
	"Hippo" : "green",
	"Hope" : "green",
	"General How" : "green",
	"Hue" : "blue",
	"Jee" : "red",
	"Jeong Jeong" : "red",
	"Jet" : "green",
	"Jin" : "green",
	"Jin Wei" : "green",
	"Joo Dee" : "green",
	"Joo Dee 2" : "green",
	"June" : "green",
	"Kaja" : "red",
	"Kenji" : "green",
	"Koh" : "other",
	"Kuruk" : "blue",
	"Kwan" : "red",
	"Kya" : "blue",
	"Kuei" : "green",
	"Lao" : "green",
	"Li" : "red",
	"Lily" : "green",
	"Lion Turtle" : "other",
	"Lo" : "red",
	"Long Feng" : "green",
	"Longshot" : "green",
	"Lu Ten" : "red",
	"Macmu-Ling" : "green",
	"Mai" : "red",
	"Meng" : "green",
	"Ming" : "red",
	"Miyuki" : "green",
	"Moku" : "green",
	"Mongke" : "red",
	"Mung" : "red",
	"Nyla" : "other",
	"Oma" : "green",
	"On Ji" : "red",
	"Painted Lady" : "other",
	"Pakku" : "blue",
	"Pao" : "green",
	"Piandao" : "red",
	"Pipsqueak" : "green",
	"Pong" : "green",
	"Poon" : "red",
	"Qin" : "red",
	"Quon" : "green",
	"Ran and Shaw" : "other",
	"Ruon-Jian" : "red",
	"Sangok" : "blue",
	"Sela" : "green",
	"Sha-Mo" : "green",
	"Shinu" : "red",
	"Shoji" : "red",
	"Shu" : "green",
	"Shyu" : "red",
	"Smellerbee" : "green",
	"Song" : "green",
	"Sozin" : "red",
	"Star" : "green",
	"Sun Warrior chief": "red",
	"Sung" : "green",
	"Ta Min" : "red",
	"Teo" : "green",
	"Than" : "green",
	"The Duke" : "green",
	"The Mechanist" : "green",
	"Tho" : "blue",
	"Tom Tom" : "red",
	"Tong" : "green",
	"Toph" : "green",
	"Ty Lee" : "red",
	"Ursa" : "red",
	"Wan Shi Tong" : "other",
	"Wei Jin" : "green",
	"Wu" : "green",
	"Xin Fu" : "green",
	"Yangchen" : "white",
	"Ying" : "green",
	"Yon Rha" : "red",
	"Yu" : "green",
	"Yue" : "blue",
	"Yugoda" : "blue",
	"Yung" : "green",
	"Zei" : "green",
	"Zhang Leader" : "green"
}