alias_dict = {
    "Sokka" : ["Wang Fire", "Captain Boomerang"],
    "Katara" : ["Sugar Queen", "Sweetness"],
    "Aang" : ["The Avatar", "Avatar", "Avatar Aang", "Kuzon", "Twinkle Toes", "Aangy"],
	"Appa" : [],
    "Kanna" : ["Grangran", "Gran Gran", "Grandmother", "Gran", "Kana"],
    "Iroh" : ["Uncle", "Uncle Iroh", "General Iroh", "The Dragon of the West", "Dragon of the West", "Mushi", "Uncle Lazy"],
    "Zuko" : ["Prince Zuko", "Angry Boy", "Lee", "Zuzu", "Blue Spirit"],
    "Zhao" : ["Commander Zhao", "Admiral Zhao"],
    "Gyatso" : ["Monk Gyatso"],
	"Momo" : [],
	"Oyagi" : ["Oyaji"],
	"Suki" : [],
	"Cabbage Merchant" : ["The Cabbage Guy"],
	"Bumi" : ["King Bumi"],
	"Flopsy" : ["Flopsie"],
	"Haru" : [],
	"Ozai" : ["Fire Lord Ozai", "Fire Lord", "The Fire Lord"],
	"Tyro" : [],
	"Hei-Bai" : ["Heibai", "Forest Spirit"],
	"Roku" : ["Avatar Roku"],
	"Kyoshi" : ["Avatar Kyoshi"],
	"Koko" : [],
	"Actor Bumi" : [],
	"Actor Iroh" : [],
	"Actor Jet" : [],
	"Actor Sokka" : [],
	"Actor Toph" : [],
	"Actor Zuko" : [],
	"Actress Azula" : [],
	"Actress Katara" : [],
	"Actress Yue" : [],
	"Arnook" : ["Chief Arnook"],
	"Azula" : ["Princess Azula"],
	"Azulon" : ["Fire Lord Azulon"],
	"Bato" : [],
	"Bosco" : [],
	"The Boulder" : ["Boulder"],
	"Canyon Guide" : [],
	"Chan" : [],
	"Chey" : [],
	"Chin" : ["General Chin", "Chin the Great"],
	"Chit Sang" : [],
	"Chong" : [],
	"Circus Master" : [],
	"Combustion Man" : ["Sparky Sparky Boom Man"],
	"Ding" : ["Old Man Ding"],
	"Dock" : ["Xu", "Bushi"],
	"Due" : [],
	"Fang" : [],
	"Fat" : [],
	"Fong" : ["General Fong"],
	"Gan Jin Leader" : [],
	"Gan Jin Scout" : [],
	"Gansu" : [],
	"Ghashiun" : [],
	"Governor" : [],
	"Governor's Wife" : [],
	"Gow" : [],
	"Guru" : ["Guru Pathik", "Pathik"],
	"Hahn" : [],
	"Hakoda" : [],
	"Ham Ghao" : ["Ham Gao"],
	"Hama" : [],
	"Hawky" : [],
	"Herbalist" : [],
	"Hide" : [],
	"Hippo" : ["The Big Bad Hippo"],
	"Hope" : [],
	"General How" : [],
	"Hue" : [],
	"Jee" : ["Lieutenant Jee"],
	"Jeong Jeong" : ["The Deserter"],
	"Jet" : [],
	"Jin" : [],
	"Jin Wei" : [],
	"Joo Dee" : [],
	"Joo Dee 2" : [],
	"June" : [],
	"Kaja" : ["Fire Sage Kaja"],
	"Kenji" : ["Zookeeper"],
	"Koh" : ["Face Stealer", "Face-Stealer"],
	"Kuruk" : ["Avatar Kuruk"],
	"Kwan" : ["Ms. Kwan"],
	"Kya" : [],
	"Kuei" : ["Earth King"],
	"Lao" : ["Lao Beifong", "Boss Man"],
	"Li" : [],
	"Lily" : [],
	"Lion Turtle" : ["Ancient One"],
	"Lo" : [],
	"Long Feng" : [],
	"Longshot" : [],
	"Lu Ten" : [],
	"Macmu-Ling" : ["Madame Macmu-Ling"],
	"Mai" : [],
	"Meng" : [],
	"Ming" : [],
	"Miyuki" : [],
	"Moku" : [],
	"Mongke" : ["Colonel Mongke"],
	"Mung" : ["General Mung"],
	"Nyla" : [],
	"Oma" : ["Master Oma"],
	"On Ji" : [],
	"Painted Lady" : ["The Lady Lady"],
	"Pakku" : ["Master Pakku"],
	"Pao" : [],
	"Piandao" : ["Swordmaster Paindao"],
	"Pipsqueak" : [],
	"Pong" : [],
	"Poon" : ["Warden Poon"],
	"Qin" : ["War Minister Qin"],
	"Quon" : [],
	"Ran and Shaw" : ["Ran and Shao"],
	"Ruon-Jian" : ["Ruon Jian"],
	"Sangok" : ["Pupil Sangok"],
	"Sela" : [],
	"Sha-Mo" : [],
	"Shinu" : ["Colonel Shinu"],
	"Shoji" : [],
	"Shu" : ["Master Shu"],
	"Shyu" : [],
	"Smellerbee" : [],
	"Song" : [],
	"Sozin" : ["Fire Lord Sozin"],
	"Star" : [],
	"Sun Warrior chief": [],
	"Sung" : ["General Sung"],
	"Ta Min" : [],
	"Teo" : [],
	"Than" : [],
	"The Duke" : ["Duke"],
	"The Mechanist" : [],
	"Tho" : [],
	"Tom" : [],
	"Tong" : ["Mayor Tong"],
	"Toph" : ["Toph Beifong", "The Blind Bandit", "The Runaway"],
	"Ty Lee" : [],
	"Ursa" : ["Lady Ursa", "Noriko"],
	"Wan Shi Tong" : ["Knowledge Spirit", "He Who Knows Ten Thousand Things"],
	"Wei Jin" : [],
	"Wu" : ["Aunt Wu"],
	"Xin Fu" : [],
	"Yangchen" : ["Avatar Yangchen"],
	"Ying" : [],
	"Yon Rha" : [],
	"Yu" : ["Master Yu"],
	"Yue" : ["Princess Yue"],
	"Yugoda" : [],
	"Yung" : ["Omashu Resistance Leader"],
	"Zei" : ["Professor Zei"],
	"Zhang Leader" : []
}